# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: yarn install
        command: yarn install
      - deploy:
        name: deploy
        command: ssh -o "StrictHostKeyChecking no" chauna@165.227.152.132 "cd ~/lkseats; git pull; yarn install; yarn run build"